Don't exit if a ulimit fails

diff --git a/bin/testwrapper b/bin/testwrapper
--- a/bin/testwrapper
+++ b/bin/testwrapper
@@ -5,7 +5,6 @@
 # Ensure only one smoker is running at any given time
 
 # set -x
-set -e
 # source $PERLBREW_ROOT/etc/bashrc
 
 # if [ -r $HOME/.cpanreporter/$PERLBREW_PERL/config.ini ]; then
@@ -34,6 +33,9 @@ fi
 
 typeset -r NEWTMPDIR=${TMPDIR:-/tmp}/testwrapper.$$
 typeset -r ID=`id -u`
+
+# Don't exit if a ulimit fails
+set -e
 
 if [[ -d /run/user/$ID ]]; then
 	typeset -r LOCKFILE=/run/user/$ID/testwrapper.pid
